import { Router } from "express";
import { Parser } from "json2csv";
import PDFDocument from "pdfkit";
import { cityCoordinates } from "../data/cityCoordinates.js";
import { cityPollutionData } from "../data/cityPollutionData.js";
import airVisualClient from "../utils/airVisualClient.js";
import {
  getRiskLevel,
  getDiseasesByRisk,
  calculateOverallAQI,
  getAQICategory,
  getRiskFromAQI,
  getDetailedDiseases,
  getHealthRecommendations,
} from "../utils/healthRisk.js";
import { getAdvisory } from "../utils/advisory.js";

// Import the city data route handler to reuse its logic
import { cityDataRouter } from "./cityData.js";

const router = Router();

// Helper function to generate CSV data
function generateCSVData(data, type = "city") {
  const json2csvParser = new Parser();
  
  if (type === "city") {
    // Format city data for CSV
    const csvData = [{
      city: data.city,
      state: data.state,
      area: data.area || "N/A",
      latitude: data.coordinates.lat,
      longitude: data.coordinates.lng,
      aqi: data.aqi,
      aqi_category: data.aqiCategory,
      pm25: data.pm25,
      pm10: data.pm10,
      o3: data.o3 || "N/A",
      no2: data.no2 || "N/A",
      so2: data.so2 || "N/A",
      co: data.co || "N/A",
      health_risk: data.risk,
      diseases: data.diseases.join("; "),
      advisory: data.advisory,
      last_updated: data.lastUpdated,
      data_source: data.source,
      location_type: data.locationType
    }];
    return json2csvParser.parse(csvData);
  } else if (type === "heatmap") {
    // Format heatmap data for CSV
    const csvData = data.points.map(point => ({
      city: point.city,
      latitude: point.lat,
      longitude: point.lng,
      pm25: point.pm25,
      pm10: point.pm10 || "N/A",
      aqi: point.aqi || "N/A",
      risk: point.risk,
      color: point.color,
      timestamp: point.timestamp || new Date().toISOString()
    }));
    return json2csvParser.parse(csvData);
  }
  
  return "";
}

// Helper function to generate PDF report
function generatePDFReport(data, res) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50
  });
  
  // Set response headers
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=${data.city}_health_report.pdf`);
  
  doc.pipe(res);
  
  // Title
  doc.fontSize(20).font('Helvetica-Bold').text('Air Quality & Health Report', { align: 'center' });
  doc.moveDown();
  
  // City Information
  doc.fontSize(16).font('Helvetica-Bold').text(`Location: ${data.city}${data.area ? `, ${data.area}` : ''}`, { underline: true });
  doc.fontSize(12).font('Helvetica').text(`State: ${data.state}`);
  doc.text(`Coordinates: ${data.coordinates.lat.toFixed(4)}, ${data.coordinates.lng.toFixed(4)}`);
  doc.text(`Last Updated: ${new Date(data.lastUpdated).toLocaleString()}`);
  doc.text(`Data Source: ${data.source || 'Static Data'}`);
  doc.moveDown();
  
  // AQI Information
  doc.fontSize(14).font('Helvetica-Bold').text('Air Quality Index (AQI)');
  doc.fontSize(12).font('Helvetica');
  doc.text(`Current AQI: ${data.aqi}`);
  doc.text(`Category: ${data.aqiCategory}`);
  doc.text(`Health Risk: ${data.risk}`);
  doc.moveDown();
  
  // Pollutant Levels
  doc.fontSize(14).font('Helvetica-Bold').text('Pollutant Concentrations');
  doc.fontSize(12).font('Helvetica');
  doc.text(`PM2.5: ${data.pm25} µg/m³`);
  doc.text(`PM10: ${data.pm10} µg/m³`);
  if (data.o3) doc.text(`O₃: ${data.o3} µg/m³`);
  if (data.no2) doc.text(`NO₂: ${data.no2} µg/m³`);
  if (data.so2) doc.text(`SO₂: ${data.so2} µg/m³`);
  if (data.co) doc.text(`CO: ${data.co} µg/m³`);
  doc.moveDown();
  
  // Health Information
  doc.fontSize(14).font('Helvetica-Bold').text('Health Impact');
  doc.fontSize(12).font('Helvetica');
  doc.text(`Associated Diseases: ${data.diseases.join(', ')}`);
  doc.text(`Health Advisory: ${data.advisory}`);
  doc.moveDown();
  
  // Recommendations
  if (data.healthRecommendations) {
    doc.fontSize(14).font('Helvetica-Bold').text('Health Recommendations');
    doc.fontSize(12).font('Helvetica');
    if (data.healthRecommendations.airPurifier) doc.text(`• ${data.healthRecommendations.airPurifier}`);
    if (data.healthRecommendations.mask) doc.text(`• ${data.healthRecommendations.mask}`);
    if (data.healthRecommendations.stayIndoor) doc.text(`• ${data.healthRecommendations.stayIndoor}`);
    if (data.healthRecommendations.carFilter) doc.text(`• ${data.healthRecommendations.carFilter}`);
  }
  
  // Footer
  doc.moveDown(2);
  doc.fontSize(10).font('Helvetica').text('Generated by SDG-3 Air Quality Dashboard', { align: 'center' });
  doc.text('For awareness and prevention only. Not medical diagnosis.', { align: 'center' });
  
  doc.end();
}

/**
 * GET /api/export/city
 * Export city-specific data
 * Query params: 
 *   - city (required)
 *   - state (required)
 *   - area (optional)
 *   - format (csv|json|pdf) - default: csv
 */
router.get("/city", async (req, res) => {
  try {
    console.log("Export route called with query:", req.query);
    const { city, state, area, format = "csv" } = req.query;
    
    if (!city || !state) {
      return res.status(400).json({ error: "City and state are required" });
    }
    
    // Create a mock request/response to reuse city data logic
    const mockReq = {
      body: { state, city, area },
      cityCache: null // No caching for export
    };
    
    let data = null;
    let errorResponse = null;
    
    // Mock response object
    const mockRes = {
      status: function(code) {
        if (code >= 400) {
          errorResponse = { status: code };
        }
        return this;
      },
      json: function(jsonData) {
        if (errorResponse) {
          errorResponse.data = jsonData;
        } else {
          data = jsonData;
        }
        return this;
      }
    };
    
    // Call the city data route handler directly
    await new Promise((resolve) => {
      // Wrap in try/catch to handle async errors
      try {
        cityDataRouter.handle(mockReq, mockRes, resolve);
      } catch (err) {
        errorResponse = { status: 500, data: { error: "Failed to fetch city data" } };
        resolve();
      }
    });
    
    if (errorResponse) {
      return res.status(errorResponse.status).json(errorResponse.data);
    }
    
    if (!data) {
      return res.status(500).json({ error: "Failed to fetch city data" });
    }
    
    // Generate appropriate response based on format
    if (format === "json") {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=${city}_data.json`);
      return res.json(data);
    } else if (format === "pdf") {
      return generatePDFReport(data, res);
    } else {
      // Default to CSV
      const csv = generateCSVData(data, "city");
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=${city}_data.csv`);
      return res.send(csv);
    }
    
  } catch (error) {
    console.error("Export error:", error);
    res.status(500).json({ error: "Failed to export data" });
  }
});

/**
 * GET /api/export/heatmap
 * Export heatmap data for all cities or filtered by state
 * Query params:
 *   - state (optional)
 *   - format (csv|json) - default: csv
 */
router.get("/heatmap", async (req, res) => {
  try {
    const { state, format = "csv" } = req.query;
    
    // Fetch heatmap data
    const url = state 
      ? `http://localhost:5000/api/heatmap?state=${encodeURIComponent(state)}`
      : "http://localhost:5000/api/heatmap";
      
    const response = await fetch(url);
    
    if (!response.ok) {
      return res.status(500).json({ error: "Failed to fetch heatmap data" });
    }
    
    const data = await response.json();
    
    if (format === "json") {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=heatmap_data${state ? `_${state}` : ''}.json`);
      return res.json(data);
    } else {
      // Default to CSV
      const csv = generateCSVData(data.data, "heatmap");
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=heatmap_data${state ? `_${state}` : ''}.csv`);
      return res.send(csv);
    }
    
  } catch (error) {
    console.error("Heatmap export error:", error);
    res.status(500).json({ error: "Failed to export heatmap data" });
  }
});

/**
 * GET /api/export/comparison
 * Export comparison data between multiple cities
 * Query params:
 *   - cities (comma-separated list)
 *   - format (csv|json) - default: csv
 */
router.get("/comparison", async (req, res) => {
  try {
    const { cities, format = "csv" } = req.query;
    
    if (!cities) {
      return res.status(400).json({ error: "Cities parameter is required" });
    }
    
    const cityList = cities.split(",").map(c => c.trim());
    const comparisonData = [];
    
    // Fetch data for each city
    for (const cityName of cityList) {
      try {
        const response = await fetch("http://localhost:5000/api/city", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ city: cityName, state: "Maharashtra" }) // Default state
        });
        
        if (response.ok) {
          const data = await response.json();
          comparisonData.push({
            city: data.city,
            state: data.state,
            aqi: data.aqi,
            aqi_category: data.aqiCategory,
            pm25: data.pm25,
            pm10: data.pm10,
            o3: data.o3 || null,
            no2: data.no2 || null,
            so2: data.so2 || null,
            co: data.co || null,
            risk: data.risk,
            diseases: data.diseases.join("; "),
            last_updated: data.lastUpdated
          });
        }
      } catch (err) {
        console.log(`Failed to fetch data for ${cityName}`);
      }
    }
    
    if (format === "json") {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=comparison_data.json`);
      return res.json({ cities: comparisonData, count: comparisonData.length });
    } else {
      // Default to CSV
      const json2csvParser = new Parser();
      const csv = json2csvParser.parse(comparisonData);
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=comparison_data.csv`);
      return res.send(csv);
    }
    
  } catch (error) {
    console.error("Comparison export error:", error);
    res.status(500).json({ error: "Failed to export comparison data" });
  }
});

export { router as exportRouter };