// Simple standalone export API for testing
import { Router } from "express";
import { cityCoordinates } from "../data/cityCoordinates.js";
import { cityPollutionData } from "../data/cityPollutionData.js";

const router = Router();

// Simple AQI calculation
function calculateOverallAQI(pollutants) {
  const pm25Aqi = Math.round((pollutants.pm25 / 100) * 100);
  const pm10Aqi = Math.round((pollutants.pm10 / 150) * 100);
  return Math.max(pm25Aqi, pm10Aqi, 20);
}

// Simple AQI category
function getAQICategory(aqi) {
  if (aqi <= 50) return { category: "Good", color: "#22c55e" };
  if (aqi <= 100) return { category: "Satisfactory", color: "#84cc16" };
  if (aqi <= 200) return { category: "Moderate", color: "#eab308" };
  if (aqi <= 300) return { category: "Poor", color: "#f97316" };
  if (aqi <= 400) return { category: "Very Poor", color: "#ef4444" };
  return { category: "Severe", color: "#7e22ce" };
}

// Simple risk assessment
function getRiskFromAQI(aqi) {
  if (aqi <= 100) return "Low";
  if (aqi <= 200) return "Medium";
  return "High";
}

// Simple diseases list
function getDiseasesByRisk(risk) {
  if (risk === "High") return ["Asthma", "COPD", "Lung Cancer", "Heart Disease", "Stroke"];
  if (risk === "Medium") return ["Asthma", "Respiratory Infections"];
  return ["Normal respiratory function"];
}

// Simple advisory
function getAdvisory(risk) {
  if (risk === "High") return "Children and elderly should avoid outdoor exertion. Everyone else should limit outdoor activities.";
  if (risk === "Medium") return "Sensitive groups should limit outdoor activities.";
  return "Air quality is acceptable for most activities.";
}

// Generate CSV manually
function generateCSVData(data) {
  const headers = [
    'city', 'state', 'area', 'latitude', 'longitude', 'aqi', 'aqi_category',
    'pm25', 'pm10', 'o3', 'no2', 'so2', 'co', 'health_risk', 'diseases',
    'advisory', 'last_updated', 'data_source', 'location_type'
  ];
  
  const values = [
    data.city,
    data.state,
    data.area || "N/A",
    data.coordinates.lat,
    data.coordinates.lng,
    data.aqi,
    data.aqiCategory,
    data.pm25,
    data.pm10,
    data.o3 || "N/A",
    data.no2 || "N/A",
    data.so2 || "N/A",
    data.co || "N/A",
    data.risk,
    data.diseases.join("; "),
    data.advisory,
    data.lastUpdated,
    data.source,
    data.locationType
  ];
  
  return headers.join(',') + '\n' + values.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',');
}

// Generate PDF-like text report
function generatePDFData(data) {
  return `Air Quality & Health Report
  
Location: ${data.city}${data.area ? `, ${data.area}` : ''}
State: ${data.state}
Coordinates: ${data.coordinates.lat.toFixed(4)}, ${data.coordinates.lng.toFixed(4)}
Last Updated: ${new Date(data.lastUpdated).toLocaleString()}
Data Source: ${data.source || 'Static Data'}

Air Quality Index (AQI)
Current AQI: ${data.aqi}
Category: ${data.aqiCategory}
Health Risk: ${data.risk}

Pollutant Concentrations
PM2.5: ${data.pm25} µg/m³
PM10: ${data.pm10} µg/m³
${data.o3 ? `O₃: ${data.o3} µg/m³` : ''}
${data.no2 ? `NO₂: ${data.no2} µg/m³` : ''}
${data.so2 ? `SO₂: ${data.so2} µg/m³` : ''}
${data.co ? `CO: ${data.co} µg/m³` : ''}

Health Impact
Associated Diseases: ${data.diseases.join(', ')}
Health Advisory: ${data.advisory}

Generated by SDG-3 Air Quality Dashboard
For awareness and prevention only. Not medical diagnosis.`;
}

// Fetch city data
async function fetchCityData(city, state, area) {
  const cityKey = city;
  const coords = cityCoordinates[cityKey];
  
  if (!coords) {
    throw new Error("City not supported");
  }
  
  // Simple fallback data
  const pollution = cityPollutionData[cityKey] || {
    pm25: 45 + Math.random() * 80,
    pm10: 78 + Math.random() * 100,
    o3: 20 + Math.random() * 30,
    no2: 20 + Math.random() * 25,
    so2: 10 + Math.random() * 15,
    co: 300 + Math.random() * 500
  };
  
  const aqi = calculateOverallAQI(pollution);
  const aqiInfo = getAQICategory(aqi);
  const risk = getRiskFromAQI(aqi);
  const diseases = getDiseasesByRisk(risk);
  const advisory = getAdvisory(risk);
  
  return {
    state: state || "Rajasthan",
    city: cityKey,
    area: area || null,
    coordinates: { lat: coords.lat, lng: coords.lng },
    pm25: Math.round(pollution.pm25 * 10) / 10,
    pm10: Math.round(pollution.pm10 * 10) / 10,
    o3: Math.round(pollution.o3 * 10) / 10,
    no2: Math.round(pollution.no2 * 10) / 10,
    so2: Math.round(pollution.so2 * 10) / 10,
    co: Math.round(pollution.co * 10) / 10,
    aqi,
    aqiCategory: aqiInfo.category,
    aqiColor: aqiInfo.color,
    risk,
    diseases,
    detailedDiseases: [],
    healthRecommendations: {},
    chartData: [],
    advisory,
    disclaimer: "For awareness and prevention only. Not medical diagnosis.",
    lastUpdated: new Date().toISOString(),
    source: "static-data",
    fallbackUsed: true,
    locationType: area ? "area" : "city",
    locationAttempted: area || cityKey
  };
}

// Export city data endpoint
router.get("/city", async (req, res) => {
  try {
    console.log("Simple export route called with query:", req.query);
    const { city, state, area, format = "csv" } = req.query;
    
    if (!city || !state) {
      return res.status(400).json({ error: "City and state are required" });
    }
    
    // Fetch city data
    const data = await fetchCityData(city, state, area);
    
    // Generate appropriate response based on format
    if (format === "json") {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=${city}_data.json`);
      return res.status(200).json(data);
    } else if (format === "pdf") {
      res.setHeader('Content-Type', 'text/plain');
      res.setHeader('Content-Disposition', `attachment; filename=${city}_health_report.txt`);
      const pdfContent = generatePDFData(data);
      return res.status(200).send(pdfContent);
    } else {
      // Default to CSV
      const csv = generateCSVData(data);
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=${city}_data.csv`);
      return res.status(200).send(csv);
    }
    
  } catch (error) {
    console.error("Export error:", error);
    res.status(500).json({ error: "Failed to export data: " + error.message });
  }
});

// Export heatmap data endpoint
router.get("/heatmap", async (req, res) => {
  try {
    const { state, format = "csv" } = req.query;
    
    // Simple heatmap data generation
    let cities = Object.entries(cityCoordinates);
    
    if (state) {
      const stateCities = {
        "Maharashtra": ["Mumbai", "Pune", "Nagpur"],
        "Delhi": ["Delhi", "Gurgaon"],
        "Rajasthan": ["Jaipur", "Jodhpur"],
        "Karnataka": ["Bengaluru"],
        "Tamil Nadu": ["Chennai"]
      };
      
      const stateCityList = stateCities[state] || [];
      cities = cities.filter(([name]) => 
        stateCityList.some(c => c.toLowerCase() === name.toLowerCase())
      );
    }
    
    const points = cities.map(([name, coords]) => {
      const pollution = cityPollutionData[name] || {
        pm25: 45 + Math.random() * 100,
        pm10: 78 + Math.random() * 120
      };
      
      const aqi = calculateOverallAQI(pollution);
      const aqiInfo = getAQICategory(aqi);
      const risk = getRiskFromAQI(aqi);
      
      return {
        city: name,
        lat: coords.lat,
        lng: coords.lng,
        pm25: Math.round(pollution.pm25),
        pm10: Math.round(pollution.pm10),
        aqi: aqi,
        aqiCategory: aqiInfo.category,
        risk: risk,
        color: risk === "High" ? "#ef4444" : risk === "Medium" ? "#eab308" : "#22c55e",
        timestamp: new Date().toISOString()
      };
    });
    
    const data = { points };
    
    if (format === "json") {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=heatmap_data${state ? `_${state}` : ''}.json`);
      return res.status(200).json({
        success: true,
        count: data.points.length,
        filter: state || "all",
        timestamp: new Date().toISOString(),
        data: data
      });
    } else {
      // Default to CSV
      const headers = ['city', 'latitude', 'longitude', 'pm25', 'pm10', 'aqi', 'risk', 'color', 'timestamp'];
      const rows = data.points.map(point => [
        point.city,
        point.lat,
        point.lng,
        point.pm25,
        point.pm10,
        point.aqi,
        point.risk,
        point.color,
        point.timestamp
      ]);
      
      const csv = headers.join(',') + '\n' + 
                  rows.map(row => row.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n');
      
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=heatmap_data${state ? `_${state}` : ''}.csv`);
      return res.status(200).send(csv);
    }
    
  } catch (error) {
    console.error("Heatmap export error:", error);
    res.status(500).json({ error: "Failed to export heatmap data" });
  }
});

export { router as exportRouter };